# Generated by Django 4.0rc1 on 2021-11-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=500)),
                ('shorted', models.CharField(max_length=20)),
                ('counter', models.PositiveIntegerField()),
            ],
        ),
    ]
