# Generated by Django 4.0rc1 on 2021-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedurl',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortedurl',
            name='full_url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='shortedurl',
            name='shorted',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
